---
- name: Execute commands from template (recursive)
  include_tasks: "{{task_file}}"

- block:
    - name: Timeout ("{{ delay * retries }}" seconds)
      fail:
        msg: "Timed out while waiting for fpc-information."
      when: (count | int >= retries | int) and fpc_pic_online.status == False

    - name: Update job log with fpc and pic status
      job_objectlog:
        job_ctx: "{{ job_ctx }}"
        status: "{{ JOBLOG_STATUS.IN_PROGRESS }}"
        message: "{{ fpc_pic_online.msg }}"
      when: (count | int >= retries | int) and fpc_pic_online.status == True

    - name: Wait for "{{ delay }}" seconds
      wait_for:
        timeout: "{{ delay }}"

    - name: Update count to ("{{ count | int + 1 }}")
      set_fact:
        try_count: "{{ count | int + 1 }}"

    - name: Call itself recursively
      include_tasks: "do_until_loop.yml"
      vars:
        count: "{{ try_count | int }}"
  when: fpc_pic_online.msg != '' and (count | int <= retries | int)
